// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fldidkikhewwvlhwxinp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsZGlka2lraGV3d3ZsaHd4aW5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNjcxMzIsImV4cCI6MjA3MTY0MzEzMn0.abf9RLrFoEf74_RkTDn278qf7KB0p70fzztAtldLkbA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});